//type actions
export const LOAD_PLAYER_ATTEMPT = 'players/LOAD_PLAYER_ATTEMPT'
export const LOAD_PLAYER_SUCCESS = 'players/LOAD_PLAYER_SUCCESS'
export const LOAD_PLAYER_FAILURE = 'players/LOAD_PLAYER_FAILURE'

export const CREATE_PLAYER_ATTEMPT = 'players/CREATE_PLAYER_ATTEMPT'
export const CREATE_PLAYER_SUCCESS = 'players/CREATE_PLAYER_SUCCESS'
export const CREATE_PLAYER_FAILURE = 'players/CREATE_PLAYER_FAILURE'

export const UPDATE_PLAYER_ATTEMPT = 'players/UPDATE_PLAYER_ATTEMPT'
export const UPDATE_PLAYER_SUCCESS = 'players/UPDATE_PLAYER_SUCCESS'
export const UPDATE_PLAYER_FAILURE = 'players/UPDATE_PLAYER_FAILURE'

export const DELETE_PLAYER_ATTEMPT = 'players/DELETE_PLAYER_ATTEMPT'
export const DELETE_PLAYER_SUCCESS = 'players/DELETE_PLAYER_SUCCESS'
export const DELETE_PLAYER_FAILURE = 'players/DELETE_PLAYER_FAILURE'
